### ISSUE TITLE
Add the corresponding chapel file for may 16?

### ISSUE THREAD

**Issue by bollu** [ysahil97/Chapel_LLVM#3]
There is a chapel file mentioned from which array initialisation code is generated. Please add the corresponding chapel file, this will make it more comprehensive.

**Comment by ysahil97** [comment]
I have made a separate top-level folder named `code_snippets`. You will be able to find that file there with the given filename.

**Comment by bollu** [comment]
Correct. But as now, only the generated `.ll` file [is available](https://github.com/ysahil97/Chapel_LLVM/tree/master/code_snippets). It would be nice if you could check in the Chapel file as well.

**Comment by bollu** [comment]
Thanks! :)
